name: lasku_applikaatio
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift: ^2.20.3
  drift_flutter: ^0.2.0
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.4
  pdf: ^3.10.1
  printing: ^5.10.4
  sqlite3_flutter_libs: ^0.5.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.16.8
  drift_dev: ^2.20.3
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
